</> YAML  

"on":
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  ftp-deploy:
    name: FTP-Übertragung
    runs-on: ubuntu-latest

    steps:
      - name: Dateien aus GitHub laden
        uses: actions/checkout@v4

      - name: Website per FTP zu dogado übertragen
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /httpdocs/
